### ISSUE TITLE
What kind of accuracy do you get?

### ISSUE THREAD

**Issue by josephernest** [karandesai-96/digit-classifier#5]
After 10 epochs, I have a  very poor accuracy, which is not far from randomly guessing the number ;)

~~~
Epoch 1, accuracy 8.62 %.
Epoch 2, accuracy 11.36 %.
Epoch 3, accuracy 11.88 %.
Epoch 4, accuracy 12.1 %.
Epoch 5, accuracy 12.77 %.
Epoch 6, accuracy 13.16 %.
Epoch 7, accuracy 13.38 %.
Epoch 8, accuracy 13.56 %.
Epoch 9, accuracy 13.79 %.
Epoch 10, accuracy 13.97 %.
Test Accuracy: 14.6%
~~~

Isn't it because the hidden layers are too small?

    layers = [784,3,4,10]

I have seen examples with layer sizes [784,256,256,10], and the accuracy was closer to 90%. 

(But probably this would be too slow? Is it the reason why you chose so few hidden nodes?)

**Comment by pabloiarriola** [comment]
Hi
wich dataset did you use? I am getting this error 
  File "main.py", line 20, in <module>
    training_data, validation_data, test_data = load_mnist()
  File "D:\Downloads\digit-classifier-master\digit-classifier-master\collect.py", line 15, in load_mnist
    training_data, validation_data, test_data = pickle.load(data_file)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x90 in position 614: ordinal not in range(128)

I downloaded the dataset that is in the repo from the book
